//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrepareReport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_AN")]
        public string ManagerFolder {
            get {
                return ((string)(this["ManagerFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Progress review.")]
        public string ManagerReportPhraseToAdd {
            get {
                return ((string)(this["ManagerReportPhraseToAdd"]));
            }
            set {
                this["ManagerReportPhraseToAdd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Weekly timesheet and invoices ({Date})\r\nHi Gorkhmaz\r\n\r\nPlease find attached time-" +
            "sheets and invoices.\r\n\r\nBest regards\r\nSasha\r\n            ")]
        public string MessageToAddInClipboard {
            get {
                return ((string)(this["MessageToAddInClipboard"]));
            }
            set {
                this["MessageToAddInClipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SoftwareAces99")]
        public string PasswordForZip {
            get {
                return ((string)(this["PasswordForZip"]));
            }
            set {
                this["PasswordForZip"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Alex\\Dropbox\\CleverCAD_Timebooking")]
        public string SourceFolder {
            get {
                return ((string)(this["SourceFolder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\CleverCAD\\Reporting")]
        public string TargetFolder {
            get {
                return ((string)(this["TargetFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\CleverCAD\\Reporting\\Archive")]
        public string TargetFolderArchive {
            get {
                return ((string)(this["TargetFolderArchive"]));
            }
            set {
                this["TargetFolderArchive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GenerateManagerReport {
            get {
                return ((bool)(this["GenerateManagerReport"]));
            }
            set {
                this["GenerateManagerReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsToSaveTasksToFiles {
            get {
                return ((bool)(this["IsToSaveTasksToFiles"]));
            }
            set {
                this["IsToSaveTasksToFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsToGenerateInvoices {
            get {
                return ((bool)(this["IsToGenerateInvoices"]));
            }
            set {
                this["IsToGenerateInvoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsToDoFileMoverTasks {
            get {
                return ((bool)(this["IsToDoFileMoverTasks"]));
            }
            set {
                this["IsToDoFileMoverTasks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inv")]
        public string SubFolderInvoices {
            get {
                return ((string)(this["SubFolderInvoices"]));
            }
            set {
                this["SubFolderInvoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Work\\Temp\\PrepareReportTest\\Src")]
        public string SourceFolderTest {
            get {
                return ((string)(this["SourceFolderTest"]));
            }
            set {
                this["SourceFolderTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Work\\Temp\\PrepareReportTest\\Trg")]
        public string TargetFolderTest {
            get {
                return ((string)(this["TargetFolderTest"]));
            }
            set {
                this["TargetFolderTest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTestMode {
            get {
                return ((bool)(this["IsTestMode"]));
            }
            set {
                this["IsTestMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\CleverCAD\\Reporting\\FilesMoverTasks")]
        public string FilesMoverTasksFolder {
            get {
                return ((string)(this["FilesMoverTasksFolder"]));
            }
            set {
                this["FilesMoverTasksFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ToYR;")]
        public string FilesMoverTasksToDo {
            get {
                return ((string)(this["FilesMoverTasksToDo"]));
            }
            set {
                this["FilesMoverTasksToDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Alex\\Dropbox\\AN_YR\\SoftwareAces\\CleverCAD")]
        public string SummarizeReportFolder {
            get {
                return ((string)(this["SummarizeReportFolder"]));
            }
            set {
                this["SummarizeReportFolder"] = value;
            }
        }
    }
}
