//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoursesFileProcessing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Work\\Docs\\Jatakas")]
        public string InputFolder {
            get {
                return ((string)(this["InputFolder"]));
            }
            set {
                this["InputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j3_.pdf")]
        public string FilePattern {
            get {
                return ((string)(this["FilePattern"]));
            }
            set {
                this["FilePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1-End")]
        public string Pages {
            get {
                return ((string)(this["Pages"]));
            }
            set {
                this["Pages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\s+\\d+$<>^\\s*\\(\\d+\\)[ ]{3,}<>Játaka Tales of the Buddha<>\\(\\d+\\)\\s+(?<name>(\\w|[" +
            " \'.,?!:+-/*()])+)<>^$")]
        public string LinesToIgnore {
            get {
                return ((string)(this["LinesToIgnore"]));
            }
            set {
                this["LinesToIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yes")]
        public string EmptyLinesTo1 {
            get {
                return ((string)(this["EmptyLinesTo1"]));
            }
            set {
                this["EmptyLinesTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{number}.txt")]
        public string OutputFileName {
            get {
                return ((string)(this["OutputFileName"]));
            }
            set {
                this["OutputFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//^\\s+\\d+[\\r\\n]+\\s+.+[\\r\\n]+\\s+.+Játaka[ \\r\\n]+")]
        public string ReportLinesByPattern {
            get {
                return ((string)(this["ReportLinesByPattern"]));
            }
            set {
                this["ReportLinesByPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NLOnlyForParagraph {
            get {
                return ((bool)(this["NLOnlyForParagraph"]));
            }
            set {
                this["NLOnlyForParagraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\s+(?<number>\\d+)[\\r\\n]+\\s+(?<name>(\\w|[’\'.,?!-: ])+)[\\r\\n]+\\s+.+Játaka[ \\r\\n]*")]
        public string StartOfNewStoryFile {
            get {
                return ((string)(this["StartOfNewStoryFile"]));
            }
            set {
                this["StartOfNewStoryFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F:\\Work\\GitHub\\DiverseAN\\NetApps\\Libs")]
        public string LibPath {
            get {
                return ((string)(this["LibPath"]));
            }
            set {
                this["LibPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ParagraphSize {
            get {
                return ((int)(this["ParagraphSize"]));
            }
            set {
                this["ParagraphSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=([;:.,!?]|[a-zA-Z’\']+))\\d+")]
        public string FootnoteRefPattern {
            get {
                return ((string)(this["FootnoteRefPattern"]));
            }
            set {
                this["FootnoteRefPattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(?<=([ ]*))\\d+(?=[.])")]
        public string FootnotePattern {
            get {
                return ((string)(this["FootnotePattern"]));
            }
            set {
                this["FootnotePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("^\\s+(?<name>(APPENDIX))[\\r\\n]+\\s+(Glossary of Terms)")]
        public string StartOfAppendix {
            get {
                return ((string)(this["StartOfAppendix"]));
            }
            set {
                this["StartOfAppendix"] = value;
            }
        }
    }
}
